allTasksData = [
  {
    title: "Czasowniki nieregularne",
    type: "table",
  
    data: {
      columnTitles: [
        "Infinitiv",
        "Präsens 3. Person",
        "Präteritum",
        "Partizip II",
        "Bedeutung"
      ],
      rowData: [
        ["backen", "backt / bäckt", "backte / buk", "gebacken","piec"],
        ["befehlen", "befiehlt", "befahl", "befohlen", "rozkazywać"],
        ["beginnen","-","begann","begonnen", "zaczynać (się)"],
        ["bieten","-","bot","geboten", "oferować"],
        ["bitten","-","bat","gebeten", "prosić"],
        ["bleiben","-","blieb","geblieben (s.)", "zostawać"],
        ["bringen","-","brachte","gebrachte", "przynosić"],
        ["denken","-","dachte","gedacht", "myśleć"],
        ["dürfen","darf","durfte","gedurft","mieć pozwolenie"],
        ["empfehlen","empfiehlt","empfahl","empfohlen","polecać"],
        ["essen","isst","aß","gegessen","jeść"],
        ["fahren","fährt","fuhr","gefahren","jechać / jeździć"],
        ["fangen","fängt","fing","gefangen","łapać"],
        ["finden","-","fand","gefunden","znajdować"],
        ["fliegen","-","flog","geflogen (s.)","latać"],
        ["fließen","-","floss","geflossen (s.)","płynąć"],
        ["frieren","-","fror","gefroren","marznąć"],
        ["geben","gibt","gab","gegeben","dawać"],
        ["gefallen","gefällt","gefiel","gefallen","podobać się"],
        ["gehen","-","ging","gegangen (s.)","iść / chodzić"],
        ["gelingen","-","gelang","gelungen (s.)","udać się / powieść"],
        ["genießen","-","genoss","genossen","rozkoszować się"],
        ["geschehen","geschieht","geschah","geschehen (s.)","wydarzać się"],
        ["gewinnen","-","gewann","gewonnen","wygrywać"],
        ["greifen","-","griff","gegriffen","sięgać"],
        ["haben","hat","hatte","gehabt","mieć"],
        ["halten","hält","hielt","gehalten","trzymać"],
        ["heben","-","hob","gehoben","podnosić"],
        ["heißen","-","hieß","geheißen","nazywać się"],
        ["helfen","hilft","half","geholfen","pomagać"],
        ["kommen","-","kam","gekommen (s.)","przychodzić"],
        ["können","kann","konnte","gekonnt","móc / umieć"],
        ["laden","lädt","lud","geladen","ładować"],
        ["lassen","lässt","ließ","gelassen","pozwalać / kazać"],
        ["laufen","läuft","lief","gelaufen (s.)","biegać"],
        ["leiden","-","litt","gelitten","cierpieć"],
        ["leihen","-","lieh","geliehen","pożyczać"],
        ["liegen","-","lag","gelegen","leżeć"],
        ["lügen","-","log","gelogen","kłamać"],
        ["messen","misst","maß","gemessen","mierzyć"],
        ["mögen","mag","mochte","gemocht","lubić"],
        ["müssen","muss","musste","gemusst","musieć"],
        ["nehmen","nimmt","nahm","genohmen","brać"],
        ["nennen","-","nannte","genannt", "nazywać"],
      ["raten","rät","riet","geraten", "radzić"],
      ["reiben","-","rieb","gerieben", "trzeć"],
      ["reißen","-","riss","gerissen", "drzeć / rwać"],
      ["reiten","-","ritt","geritten (s.)", "jeździć konno"],
      ["rennen","-","rannte","gerannt (s.)", "pędzić / biec"],
      ["rufen", "-", "rief", "gerufen", "wołać"],
        
      ],
    },
  }
];
