allTasksData = [
  {
    title:
      "Przyimki",
    type: "fillInBlanks",

    data: {
      items: [
        { text: "Idę do %% (szkoła), do %% (ogród), do %% (park)", expectedAnswers: ["szkoły", "ogrodu", "parku"] },
        { text: "Idę do %% (lekarz)", expectedAnswers: ["lekarza"] },
        { text: "Stać się podobnym do %% (ktoś inny)", expectedAnswers: ["kogoś innego"] },
        { text: "Specjalista do spraw %% (zarządzanie)", expectedAnswers: ["zarządzania"] },
        { text: "Kot jest między %% (butelki)", expectedAnswers: ["butelkami"] },
        { text: "Pójdę na %% (siłownia), na %% (poczta), na %% (lotnisko), na %% (koncert), na %% (obiad)", expectedAnswers: ["siłownię", "pocztę", "lotnisko", "koncert", "obiad"] },
        { text: "Jestem na %% (stadion), na %% (film), na %% (obiad), na %% (siłownia)", expectedAnswers: ["stadionie", "filmie", "obiedzie", "siłowni"] },
        { text: "Kot siedzi na %% (stół)", expectedAnswers: ["stole"] },
        { text: "Kot wszedł na %% (stół)", expectedAnswers: ["stół"] },
        { text: "Otwartość na %% (każda chwila)", expectedAnswers: ["każdą chwilę"] },
        { text: "Pójdę na %% (spotkanie) jutro", expectedAnswers: ["spotkanie"] },
        { text: "Jestem na  (spotkanie)", expectedAnswers: ["spotkaniu"] },
        { text: "Niech ktoś zadzwoni na %% (policja)!", expectedAnswers: ["policję"] },
        { text: "Postępowanie na %% (wypadek) pożaru (pożar).", expectedAnswers: ["wypadek"] },
        { text: "%% (Moja dziewczyna) nie zależy na %% (kontynułowanie związek)", expectedAnswers: ["Mojej dziewczynie", "kontynułowaniu związku"] },
        { text: "On wygląda na %% (mądry)", expectedAnswers: ["mądrego"] },
        { text: "Idę nad %% (morze), nad %% (Wisła)", expectedAnswers: ["morze", "Wisłę"] },
        { text: "Jestem nad %% (morze), nad %% (Wisła)", expectedAnswers: ["morzem", "Wisłą"] },
        { text: "Kot jest nad %% (rybka)", expectedAnswers: ["rybką"] },
        { text: "Kot jest naprzeciwko %% (pies)", expectedAnswers: ["psa"] },
        { text: "Na podstawie %% (prawo międzynarodowy)", expectedAnswers: ["prawa międzynarowego"] },
        { text: "Na podstawie powieści %% (Jan Brzechwa)", expectedAnswers: ["Jana Brzechwy"] },
        { text: "Kot i pies są na wprost %%", expectedAnswers: ["siebie"] },
        { text: "Jan siedzi na wprost %% (Ania)", expectedAnswers: ["Ani"] },
        { text: "Dzisiaj pogadam z %% (Ania) o %% (bilety lotnicze)", expectedAnswers: ["Anią", "biletach lotniczych"] },
        { text: "Chodzi o %% (prezenty) dla %% (dzieci)", expectedAnswers: ["prezenty", "dzieci"] },
        { text: "Kot jest obok %% (pies)", expectedAnswers: ["psa"] },
        { text: "Lekarz stoi obok %% (pielęgniarka)", expectedAnswers: ["pielęgniarki"] },
        { text: "Wracam od %% (lekarz), od %% (babcia)", expectedAnswers: ["lekarza", "babci"] },
        { text: "Oprócz %% (Bartek), nikt nie trafi do %% (więzienie)", expectedAnswers: ["Bartka", "więzienia"] },
        { text: "Oprócz %% (standardowe rzeczy)", expectedAnswers: ["standardowych rzeczy"] },
        { text: "Po %% (zmiana + praca)", expectedAnswers: ["zmianie pracy"] },
        { text: "Po %% (dwa + lata)", expectedAnswers: ["dwóch latach"] },
        { text: "Kot chodzi po %% (dach)", expectedAnswers: ["dachu"] },
        { text: "Po %% (słuchanie)", expectedAnswers: ["słuchaniu"] },
        { text: "Jadę po %% (córka) na %% (dworzec)", expectedAnswers: ["córkę","dworzec"] },
        { text: "Zadzwoń po %% (pogotowie)", expectedAnswers: ["pogotowie"] },
        { text: "Kobieta wpadła pod %% (samochód)", expectedAnswers: ["samochód"] },
        { text: "Klucz leżał pod %% (samochód)", expectedAnswers: ["samochodem"] },
        { text: "Kot jest pod %% (krzesło)", expectedAnswers: ["krzesłem"] },
        { text: "Wziąć to pod %% (uwaga)", expectedAnswers: ["uwagę"] },
        { text: "Badać pod %% (ten + kąt)", expectedAnswers: ["tym kątem"] },
        { text: "", expectedAnswers: [""] },
        { text: "", expectedAnswers: [""] },
      ],
    },
  },
];